from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader
import nonebot
import pytest

nonebot.init()

from zhenxun import ui
from zhenxun.plugins.moesekai.adapters import best30_renderer
from zhenxun.plugins.moesekai.b30 import B30Entry, B30Result
from zhenxun.plugins.moesekai.providers.suite import SuiteProfile


class _FakeSettings:
    b30_viewport_width = 980


def _sample_result() -> B30Result:
    return B30Result(
        entries=[
            B30Entry(
                rank=index,
                music_id=index,
                title=f"测试歌曲 {index}",
                difficulty="master",
                difficulty_label="MASTER",
                level=30,
                constant=30.0,
                user_rating=30.0,
                play_result="AP",
                note_count=1000,
            )
            for index in range(1, 31)
        ],
        average=30.0,
        candidate_count=30,
        ap_count=30,
        fc_count=0,
        missing_constants_count=0,
        total_result_count=30,
    )


@pytest.mark.asyncio
async def test_render_best30_image_uses_ui_template_with_sources(
    monkeypatch: pytest.MonkeyPatch,
):
    async def fake_render_template(path, data, **kwargs):
        assert path == best30_renderer._TEMPLATE_PATH
        assert data["sources"] == ["Suite", "Constants"]
        assert data["fontUris"]["regular"].endswith(
            "resources/font/HarmonyOS_Sans_SC_Regular.ttf"
        )
        assert kwargs["viewport"] == {"width": 980, "height": 10}
        assert kwargs["is_page"] is True
        return b"best30-image"

    monkeypatch.setattr(
        "zhenxun.plugins.moesekai.adapters.best30_renderer.get_settings",
        lambda: _FakeSettings(),
    )
    monkeypatch.setattr(ui, "render_template", fake_render_template)

    image = await best30_renderer.render_best30_image(
        server="jp",
        profile=SuiteProfile(
            "1234567890123",
            "测试玩家",
            88,
            1779774627,
            name_color="#ff9900",
        ),
        result=_sample_result(),
        sources=["Suite", "Constants"],
        warnings=[],
    )

    assert image == b"best30-image"


def test_best30_template_renders_footer_sources():
    template_dir = Path(best30_renderer._TEMPLATE_PATH).parent
    env = Environment(loader=FileSystemLoader(str(template_dir)))
    template = env.get_template("index.html")

    html = template.render(
        server="jp",
        serverLabel="日服",
        profile={
            "name": "测试玩家",
            "user_id": "123",
            "rank": 88,
            "name_color": "#ff9900",
        },
        updatedText="2026-05-28 12:00",
        averageText="30.00",
        fontUris={
            "regular": "file:///resources/font/HarmonyOS_Sans_SC_Regular.ttf",
            "medium": "file:///resources/font/HarmonyOS_Sans_SC_Medium.ttf",
            "bold": "file:///resources/font/HarmonyOS_Sans_SC_Bold.ttf",
        },
        entries=[
            {
                "title": "测试歌曲",
                "difficulty": "master",
                "difficulty_label": "MASTER",
                "level": 0,
                "constant": 30.0,
                "user_rating": 30.0,
                "play_result": "AP",
                "jacket_uri": "",
            }
        ],
        candidateCount=0,
        apCount=0,
        fcCount=0,
        missingConstantsCount=0,
        totalResultCount=0,
        sources=[
            "suite数据来源：https://suite-api.haruki.seiunx.com",
            "定数来源：https://moe.exmeaning.com",
        ],
        warnings=["0 首曲绘缺失"],
    )

    assert "HarmonyOS Sans SC" in html
    assert "社区定数，仅供娱乐" in html
    assert "AP = 定数" in html
    assert 'style="color: #ff9900 !important;"' in html
    assert "Lv.88" in html
    assert "UID：123 · JP" in html
    assert "diff-master" in html
    assert "                        30" in html
    assert "30.0" in html
    assert "→ 30.0" in html
    assert "ALL PERFECT" in html
    assert "suite数据来源：https://suite-api.haruki.seiunx.com" in html
    assert " / " in html
    assert "定数来源：https://moe.exmeaning.com" in html
    assert "Designed &amp; Generated by PoleSudBot" in html
    assert "key=" not in html
    assert "公式：" not in html
    assert "资源状态" not in html
    assert "计入" not in html
    assert "缺定数" not in html
    assert "#05" not in html
    assert "Lv.30" not in html
    assert "notes" not in html.lower()
