from __future__ import annotations

from .application.service import moesekai_app

validate_game_id = moesekai_app.validate_game_id
format_time = moesekai_app.format_time
migrate_legacy_bindings = moesekai_app.migrate_legacy_bindings
seed_default_aliases = moesekai_app.seed_default_aliases
sync_music_aliases = moesekai_app.sync_music_aliases
handle_bind = moesekai_app.handle_bind
handle_unbind = moesekai_app.handle_unbind
handle_default_server = moesekai_app.handle_default_server
handle_visibility = moesekai_app.handle_visibility
handle_personal_archive = moesekai_app.handle_personal_archive
handle_query_archive = moesekai_app.handle_query_archive
handle_prediction = moesekai_app.handle_prediction
handle_update = moesekai_app.handle_update
handle_ycx = moesekai_app.handle_ycx
handle_deck = moesekai_app.handle_deck
handle_story = moesekai_app.handle_story
handle_random_manga = moesekai_app.handle_random_manga
handle_manga_by_id = moesekai_app.handle_manga_by_id
handle_character = moesekai_app.handle_character
handle_multiplier = moesekai_app.handle_multiplier
handle_alias_command = moesekai_app.handle_alias_command
handle_admin_blacklist = moesekai_app.handle_admin_blacklist
handle_admin_query_binding = moesekai_app.handle_admin_query_binding
handle_live_toggle = moesekai_app.handle_live_toggle
handle_live_subscription = moesekai_app.handle_live_subscription
handle_new_card_toggle = moesekai_app.handle_new_card_toggle
handle_test_live_reminder = moesekai_app.handle_test_live_reminder
handle_test_new_card_reminder = moesekai_app.handle_test_new_card_reminder
build_auto_update_notifications = moesekai_app.build_auto_update_notifications
dispatch_new_card_notifications = moesekai_app.dispatch_new_card_notifications
dispatch_live_reminders = moesekai_app.dispatch_live_reminders
